name: FlagsPlayer
version: 1.0.0
description: Module that adds player flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: alshain01.FlagsPlayer.FlagsPlayer
depend: [Flags]